---
# defaults file for kvm_provision
base_image_name: CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
base_image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/{{ base_image_name }}
base_image_sha: "{{ base_image_url }}.SHA256SUM"
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: centos-dev
vm_vcpus: 4
vm_ram_mb: 4096
vcpu_pinning:
        0: 2
        1: 3
        2: 4
        3: 5
vm_net: default
vm_root_pass: redhat
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
